<template>
  <div>
    <force-simulation ref="forceSimulation"></force-simulation>
    <button @click="reset">重置</button>
  </div>
</template>
<script>
import ForceSimulation from "@/components/d3-force-simulation/index.vue";
export default {
  components: {
    ForceSimulation,
  },
  data() {
    return {
      data: {
        nodes: [
          {
            id: "100430",
            name: "程恒采购商",
            group: 3,
          },
          {
            id: "100429",
            name: "程恒供应商",
            group: 3,
          },
          {
            id: "100402",
            name: "重庆市轨道交通(集团)有限公司",
            group: 3,
          },
          {
            id: "100237",
            name: "阿拉尔市富丽达纤维有限公司",
            group: 3,
          },
          {
            id: "100238",
            name: "阿拉尔飞龙纺织有限公司",
            group: 3,
          },
          {
            id: "100300",
            name: "深圳市思勉信息咨询有限公司",
            group: 2,
          },
          {
            id: "100231",
            name: "北京妈咪宝贝传媒发展有限公司有限公司",
            group: 3,
          },
          {
            id: "100266",
            name: "唐蕴廉链条企业",
            group: 3,
          },
          {
            id: "100264",
            name: "浏阳市签发农机专业合作社",
            group: 2,
          },
          {
            id: "100360",
            name: "司马迁",
            group: 3,
          },
          {
            id: "100361",
            name: "司马光",
            group: 2,
          },
          {
            id: "100265",
            name: "唐蕴廉核心企业核心",
            group: 3,
          },
          {
            id: "1000000522",
            name: "重庆市轨道交通(集团)有限公司",
            group: 3,
          },
          {
            id: "100640",
            name: "程婴采购商",
            group: 3,
          },
        ],
        edges: [
          {
            source: "100430",
            target: "100429",
            value: 20,
            position: "down",
            debitTotalAmount: 326678510,
            debitSuccessAmount: 326677286,
            debitTotalNumber: 11,
            debitSuccessNumber: 10,
          },
          {
            source: "100429",
            target: "100402",
            value: 19,
            position: "middle",
            debitTotalAmount: 845711,
            debitSuccessAmount: 0,
            debitTotalNumber: 4,
            debitSuccessNumber: 0,
          },
          {
            source: "100402",
            target: "100237",
            value: 18,
            position: "middle",
            debitTotalAmount: 24378,
            debitSuccessAmount: 0,
            debitTotalNumber: 5,
            debitSuccessNumber: 0,
          },
          {
            source: "100237",
            target: "100238",
            value: 17,
            position: "down",
            debitTotalAmount: 1000,
            debitSuccessAmount: 0,
            debitTotalNumber: 1,
            debitSuccessNumber: 0,
          },
          {
            source: "100238",
            target: "100300",
            value: 16,
            position: "middle",
            debitTotalAmount: 1000000,
            debitSuccessAmount: 1000000,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100238",
            target: "100237",
            value: 16,
            position: "up",
            debitTotalAmount: 1000000,
            debitSuccessAmount: 0,
            debitTotalNumber: 1,
            debitSuccessNumber: 0,
          },
          {
            source: "100429",
            target: "100231",
            value: 19,
            position: "middle",
            debitTotalAmount: 503115,
            debitSuccessAmount: 500000,
            debitTotalNumber: 3,
            debitSuccessNumber: 1,
          },
          {
            source: "100231",
            target: "100237",
            value: 18,
            position: "middle",
            debitTotalAmount: 850000,
            debitSuccessAmount: 850000,
            debitTotalNumber: 2,
            debitSuccessNumber: 2,
          },
          {
            source: "100231",
            target: "100238",
            value: 18,
            position: "middle",
            debitTotalAmount: 500000,
            debitSuccessAmount: 500000,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100429",
            target: "100266",
            value: 19,
            position: "down",
            debitTotalAmount: 500000,
            debitSuccessAmount: 500000,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100266",
            target: "100429",
            value: 18,
            position: "up",
            debitTotalAmount: 10998,
            debitSuccessAmount: 10998,
            debitTotalNumber: 2,
            debitSuccessNumber: 2,
          },
          {
            source: "100266",
            target: "100237",
            value: 18,
            position: "middle",
            debitTotalAmount: 4000,
            debitSuccessAmount: 4000,
            debitTotalNumber: 2,
            debitSuccessNumber: 2,
          },
          {
            source: "100266",
            target: "100430",
            value: 18,
            position: "down",
            debitTotalAmount: 997,
            debitSuccessAmount: 997,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100429",
            target: "100264",
            value: 19,
            position: "middle",
            debitTotalAmount: 200000,
            debitSuccessAmount: 0,
            debitTotalNumber: 1,
            debitSuccessNumber: 0,
          },
          {
            source: "100429",
            target: "100360",
            value: 19,
            position: "middle",
            debitTotalAmount: 112221,
            debitSuccessAmount: 105555,
            debitTotalNumber: 3,
            debitSuccessNumber: 2,
          },
          {
            source: "100360",
            target: "100361",
            value: 18,
            position: "middle",
            debitTotalAmount: 1102450000,
            debitSuccessAmount: 1102450000,
            debitTotalNumber: 7,
            debitSuccessNumber: 7,
          },
          {
            source: "100360",
            target: "100265",
            value: 18,
            position: "middle",
            debitTotalAmount: 50000,
            debitSuccessAmount: 50000,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100265",
            target: "100266",
            value: 17,
            position: "middle",
            debitTotalAmount: 2138424691,
            debitSuccessAmount: 2015292568,
            debitTotalNumber: 10,
            debitSuccessNumber: 9,
          },
          {
            source: "100265",
            target: "100429",
            value: 17,
            position: "middle",
            debitTotalAmount: 25000,
            debitSuccessAmount: 25000,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100429",
            target: "100237",
            value: 19,
            position: "middle",
            debitTotalAmount: 110000,
            debitSuccessAmount: 0,
            debitTotalNumber: 2,
            debitSuccessNumber: 0,
          },
          {
            source: "100429",
            target: "1000000522",
            value: 19,
            position: "middle",
            debitTotalAmount: 13152,
            debitSuccessAmount: 0,
            debitTotalNumber: 3,
            debitSuccessNumber: 0,
          },
          {
            source: "1000000522",
            target: "100402",
            value: 18,
            position: "middle",
            debitTotalAmount: 5252,
            debitSuccessAmount: 0,
            debitTotalNumber: 1,
            debitSuccessNumber: 0,
          },
          {
            source: "100429",
            target: "100238",
            value: 19,
            position: "middle",
            debitTotalAmount: 12360,
            debitSuccessAmount: 12360,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100429",
            target: "100640",
            value: 19,
            position: "down",
            debitTotalAmount: 1000,
            debitSuccessAmount: 0,
            debitTotalNumber: 1,
            debitSuccessNumber: 0,
          },
          {
            source: "100640",
            target: "100429",
            value: 18,
            position: "up",
            debitTotalAmount: 1599999999,
            debitSuccessAmount: 1599999999,
            debitTotalNumber: 3,
            debitSuccessNumber: 3,
          },
          {
            source: "100429",
            target: "100430",
            value: 19,
            position: "up",
            debitTotalAmount: 998,
            debitSuccessAmount: 998,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
          {
            source: "100430",
            target: "100266",
            value: 20,
            position: "up",
            debitTotalAmount: 10999999,
            debitSuccessAmount: 10000000,
            debitTotalNumber: 2,
            debitSuccessNumber: 1,
          },
        ],
      },
    };
  },
  mounted() {
    this.$nextTick(() => {
      this.$refs.forceSimulation.init(this.data);
    });
  },
  methods: {
    reset() {
      const data = {
        nodes: [
          {
            id: "100430",
            name: "程恒采购商",
            group: 3,
          },
          {
            id: "100429",
            name: "程恒供应商",
            group: 2,
          },
          {
            id: "100266",
            name: "唐蕴廉链条企业",
            group: 1,
          },
        ],
        edges: [
          {
            source: "100430",
            target: "100429",
            value: 20,
            position: "down",
            debitTotalAmount: 326678510,
            debitSuccessAmount: 326677286,
            debitTotalNumber: 11,
            debitSuccessNumber: 10,
          },
          {
            source: "100266",
            target: "100430",
            value: 19,
            position: "up",
            debitTotalAmount: 997,
            debitSuccessAmount: 997,
            debitTotalNumber: 1,
            debitSuccessNumber: 1,
          },
        ],
      };
      this.$refs.forceSimulation.reset(data);
    },
  },
};
</script>
<style lang="scss"></style>
